package org.itmo.mse.constants;

public enum Change {
    DUNGEON_LEVEL, BACKPACK_OPENED_TRUE, BACKPACK_OPENED_FALSE, PLAYER_POSITION, PLAYER_INFO,
    SELECTED_INDEX_ITEM, ADD_REMOVE_ITEM, DEATH_MOB
}
